server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payment_db}
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:newpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/ecommerce}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.messaging.exchange=${MESSAGING_EXCHANGE:ecommerce.exchange}
app.messaging.payment-requested-queue=${PAYMENT_REQUESTED_QUEUE:payment.requested.queue}
app.messaging.payment-requested-routing-key=${PAYMENT_REQUESTED_ROUTING_KEY:payment.requested}
app.messaging.payment-initialized-routing-key=${PAYMENT_INITIALIZED_ROUTING_KEY:payment.initialized}
app.messaging.payment-succeeded-routing-key=${PAYMENT_SUCCEEDED_ROUTING_KEY:payment.succeeded}
app.messaging.payment-failed-routing-key=${PAYMENT_FAILED_ROUTING_KEY:payment.failed}

app.iyzico.api-key=${IYZICO_API_KEY:}
app.iyzico.secret-key=${IYZICO_SECRET_KEY:}
app.iyzico.base-url=${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
app.iyzico.callback-url=${IYZICO_CALLBACK_URL:}
app.iyzico.locale=${IYZICO_LOCALE:tr}
app.iyzico.currency=${IYZICO_CURRENCY:TRY}
app.iyzico.buyer-name=${IYZICO_BUYER_NAME:Sandbox}
app.iyzico.buyer-surname=${IYZICO_BUYER_SURNAME:User}
app.iyzico.buyer-email=${IYZICO_BUYER_EMAIL:sandbox@example.com}
app.iyzico.buyer-identity-number=${IYZICO_BUYER_IDENTITY_NUMBER:11111111111}
app.iyzico.buyer-gsm-number=${IYZICO_BUYER_GSM_NUMBER:+905350000000}
app.iyzico.buyer-ip=${IYZICO_BUYER_IP:127.0.0.1}
app.iyzico.address=${IYZICO_ADDRESS:Altunizade Mah. Inci Cikmazi Sokak No: 3 Uskudar Istanbul}
app.iyzico.city=${IYZICO_CITY:Istanbul}
app.iyzico.country=${IYZICO_COUNTRY:Turkey}
app.iyzico.zip-code=${IYZICO_ZIP_CODE:34742}
